; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:edgebox-esp-100]
platform = espressif32
board = edgebox-esp-100
framework = arduino
monitor_speed = 115200
board_build.bootloader = qio
extra_scripts = pre:extra_script.py
upload_port =  	/dev/cu.wchusbserial5A6C0362011
monitor_port =  /dev/cu.wchusbserial5A6C0362011
lib_deps = 
	https://github.com/madleech/Button.git
	https://github.com/elastra21/EdgeBox_ESP_100.git
	arduino-libraries/Ethernet@^2.0.2
	links2004/WebSockets@2.3.7
	bblanchon/ArduinoJson@6.20.0
	mathieucarbou/MycilaWebSerial@^7.0.1
  arkhipenko/TaskScheduler@^3.8.5
	emelianov/modbus-esp8266@^4.1.0
build_flags   = 
    ; para poder usar Serial.printf()
    ; Nivel 3=Info, 4=Debug, 5=Verbose (reduce BLE spam)
    -DCORE_DEBUG_LEVEL=3
board_build.partitions = huge_app.csv

; Configuración para tests embebidos en ESP32
; [env:test]
; platform = espressif32
; board = edgebox-esp-100
; framework = arduino
; monitor_speed = 115200
; test_framework = unity
; test_port = /dev/cu.SLAB_USBtoUART8
; upload_port = /dev/cu.SLAB_USBtoUART8
; lib_deps = 
; 	bblanchon/ArduinoJson@6.20.0
; build_flags = 
;     -DUNIT_TEST
;     -DCORE_DEBUG_LEVEL=5





